# Take-Home Assignment Week 2
## Santiago Bernheim

### Part 1 - Numpy
Use this dataset for the first 4 questions.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])





1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [44]:
import numpy as np

# Define custom NumPy arrays
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9], 
              [10, 11, 12]])

# Vertical stacking
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((A, B))
print("\nHorizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

In [45]:
# Find common elements (intersection)
common_elements = np.intersect1d(A, B)
print("\nCommon Elements:\n", common_elements)

#Example where there are common elements
A2 = np.array([1,2,3,4,5,6])
B2 = np.array([3,6,9,12,15])

common_elements2 = np.intersect1d(A2, B2)
print("\nCommon Elements between A2 and B2:\n", common_elements2)


Common Elements:
 []

Common Elements between A2 and B2:
 [3 6]


3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [46]:
# Extract numbers between 5 and 10 (inclusive) from A
range_start = 5
range_end = 10

# Method 1: Using np.where()
indices = np.where((A >= range_start) & (A <= range_end))
elements_in_range_where = A[indices]
print(f"Elements in range [{range_start}, {range_end}] (using np.where()):\n", elements_in_range_where)

# Method 2: Using boolean masks
mask = (A >= range_start) & (A <= range_end)
elements_in_range_mask = A[mask]
print(f"Elements in range [{range_start}, {range_end}] (using boolean masks):\n", elements_in_range_mask)

#Example with a different array and range.
A3 = np.array([2,5,8,11,14,17,20,23])
range_start2 = 10
range_end2 = 20

indices2 = np.where((A3 >= range_start2) & (A3 <= range_end2))
elements_in_range_where2 = A3[indices2]
print(f"Elements in A3 range [{range_start2}, {range_end2}] (using np.where()):\n", elements_in_range_where2)

mask2 = (A3 >= range_start2) & (A3 <= range_end2)
elements_in_range_mask2 = A3[mask2]
print(f"Elements in A3 range [{range_start2}, {range_end2}] (using boolean masks):\n", elements_in_range_mask2)

Elements in range [5, 10] (using np.where()):
 [5 6]
Elements in range [5, 10] (using boolean masks):
 [5 6]
Elements in A3 range [10, 20] (using np.where()):
 [11 14 17 20]
Elements in A3 range [10, 20] (using boolean masks):
 [11 14 17 20]


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

mask = np.logical_and(iris_2d[:, 2] > 1.5, iris_2d[:, 0] < 5.0)

filtered_cols = iris_2d[mask]

print("The filtered array with petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is:")
print(filtered_cols)

The filtered array with petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 is:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]



### Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [48]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.iloc[::20][['Manufacturer', 'Model', 'Type']]

print("The filtered DATA is:")

print(filtered_df)

The filtered DATA is:
   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [49]:
df_2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_2['Max.Price'].fillna(df['Max.Price'].mean(), inplace= True)
df_2['Min.Price'].fillna(df['Min.Price'].mean(), inplace= True)

print(df_2)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

/var/folders/4c/654xyldd6qgb9x6zjs5gt9mm0000gn/T/ipykernel_54105/909119990.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_2['Max.Price'].fillna(df['Max.Price'].mean(), inplace= True)
/var/folders/4c/654xyldd6qgb9x6zjs5gt9mm0000gn/T/ipykernel_54105/909119990.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are settin

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

In [50]:
df_3  = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_summed = df_3.sum(axis=1) # genereate sum for each row.
filtered_df_3 = df_3[row_summed > 100]
print(filtered_df_3)

     0   1   2   3
4   36  27  34  11
6   28  29  15  31
7   27  17  30  29
11  33  34  17  19
12  29  36  21  19
